"""
Django settings for blog project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/

Django Common Settings for development and production environments
"""

import os
from datetime import datetime

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pygments',
    'markdownx',
    'captcha',
    'myblog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
]

# CSP Variables
CSP_DEFAULT_SRC = ("'self'",
                   "https://c.disquscdn.com/next/embed/",
                   "https://disqus.com/next/",
                   "https://disqus.com/embed/comments/",
                   "https://disqus.com/home/preload/",
                   "https://links.services.disqus.com/api/",
                   "https://www.google.com/recaptcha/",
                   )

CSP_STYLE_SRC = ("'self'", "'unsafe-inline'",
                 "https://fonts.googleapis.com/",
                 "https://c.disquscdn.com/next/embed/styles/",
                 )

CSP_SCRIPT_SRC = ("'self'",
                  "'unsafe-inline'",
                  "'unsafe-eval'",
                  "https://polyfill.io/v3/",
                  "https://cdn.jsdelivr.net/npm/mathjax@3.0.0/es5/",
                  "https://gunduzhuseyn.disqus.com/embed.js",
                  "https://c.disquscdn.com/next/embed/",
                  "https://www.google.com/recaptcha/",
                  "https://www.gstatic.com/recaptcha/",
                  )
CSP_IMG_SRC = ("'self'",
               "https://referrer.disqus.com/juggler/",
               "https://c.disquscdn.com/next/embed/assets/img/",
               "http://cdn.viglink.com/images/",
               "http://links.services.disqus.com/api/",
               )
CSP_FONT_SRC = ("'self'",
                "https://fonts.gstatic.com/",
                "https://cdn.jsdelivr.net/npm/mathjax@3.0.0/es5/output/chtml/fonts/woff-v2/",
                )

ROOT_URLCONF = 'blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Markdownx Settings
MARKDOWNX_IMAGE_MAX_SIZE = {'size': (900, 900), 'quality': 100}

MARKDOWNX_MEDIA_PATH = datetime.now().strftime('markdownx/%Y/%m/%d')

MARKDOWNX_MARKDOWN_EXTENSIONS = [
    'markdown.extensions.extra',
    'markdown.extensions.codehilite',
    'markdown.extensions.mdx_math'
]

MARKDOWNX_MARKDOWN_EXTENSION_CONFIGS = {
    'codehilite': {
        'linenums': True
    },
}

# Google ReCAPTCHA Settings
RECAPTCHA_REQUIRED_SCORE = 0.65

RECAPTCHA_PUBLIC_KEY = '6Le7ZqYZAAAAANCx3Sf1IXqBOeGlPIxw1TvrMF4K'
